# Generated by Django 4.2.4 on 2023-08-27 16:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_engin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_category', models.CharField(max_length=100)),
                ('commtentaire_category', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=15)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee_fabrication', models.PositiveIntegerField()),
                ('date_achat', models.DateField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_engin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automob_ecole.category_engin')),
            ],
        ),
        migrations.CreateModel(
            name='Moniteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('date_embauche', models.DateField()),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField()),
                ('duree', models.DurationField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automob_ecole.engin')),
            ],
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lecon', models.DateTimeField()),
                ('duree', models.DurationField()),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('moniteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automob_ecole.moniteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automob_ecole.engin')),
            ],
        ),
        migrations.AddField(
            model_name='engin',
            name='moniteur_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automob_ecole.moniteur'),
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('equip_visuel', models.CharField(choices=[('Oui', 'OUI'), ('Non', 'NON')], max_length=3)),
                ('app_auditif', models.CharField(choices=[('Oui', 'OUI'), ('Non', 'NON')], max_length=3)),
                ('handicap', models.CharField(choices=[('Oui', 'OUI'), ('Non', 'NON')], max_length=3)),
                ('date_naissance', models.DateTimeField()),
                ('permis', models.CharField(max_length=4)),
                ('nationalite', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('autheur_enreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
