# Generated by Django 4.2.4 on 2023-08-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automob_ecole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moniteur',
            name='photo',
            field=models.ImageField(default='1', upload_to='media/moniteur'),
            preserve_default=False,
        ),
    ]
