# Generated by Django 4.2.4 on 2023-08-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automob_ecole', '0002_moniteur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moniteur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='moniteur'),
        ),
    ]
