# Generated by Django 4.2.4 on 2023-08-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automob_ecole', '0004_moniteur_autheur_enreg_moniteur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='inscription'),
        ),
        migrations.AlterField(
            model_name='moniteur',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
